DigiFood/urls.py
from django.contrib import admin
from django.urls import path, include

from filebrowser.sites import site

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('account/', include('accounts.urls',)),
    path('product/', include(('products.urls', 'products'), namespace='products')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('favorite/', include(('favorites.urls', 'favorites'), namespace='favorites')),
    path('pay/', include(('zarinpal.urls', 'zarinpal'), namespace='zarinpal')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (blog_view,
                    post_list,
                    post_detail,
                    search,

                    post_create,
                    post_update,
                    post_delete,

                    post_like,

                    comment_approve,
                    comment_remove,
                    post_publish,
                    )

urlpatterns = [
    path('', blog_view, name='blog_view'),
    path('posts/', post_list, name='post_list'),
    path('posts/<int:id>/<slug:slug>/detail/', post_detail, name='post_detail'),
    path('posts/<slug:cat_slug>/category/', post_list, name='post_category'),
    path('posts/<int:id>/<slug:slug>/like/', post_like, name='post_like'),

    path('posts/create/', post_create, name='post_create'),
    path('posts/<int:id>/<slug:slug>/update/', post_update, name='post_update'),
    path('posts/<int:id>/<slug:slug>/delete/', post_delete, name='post_delete'),



    # path('posts/add', PostCreate.as_view(), name='post_create'),
    # path('posts/<int:id>/<slug:slug>/update',
    #      PostUpdate.as_view(), name='post_update'),
    # path('posts/<int:id>/<slug:slug>/delete',
    #      PostDelete.as_view(), name='post_delete'),

    path('post/<int:id>/<slug:slug>/publish/',
         post_publish, name='post_publish'),

    path('result/', search, name='search'),

    path('comment/<int:id>/approve',
         comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove',
         comment_remove, name='comment_remove'),

]

cart/urls.py
from django.urls import path
from .views import(
    cart, add_to_cart,
    remove_from_cart,
    clear_from_cart,
    bank_view,
    get_total_price,
    clear_cart,
    add_to_cart_product_list,


)

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<product_id>/', add_to_cart, name='add_to_cart'),
    path('product-list/add/<product_id>/',
         add_to_cart_product_list, name='add_to_cart_product_list'),
    path('remove/<product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/<product_id>/', clear_from_cart, name='clear_from_cart'),
    path('destroy/', clear_cart, name='clear_cart'),
    path('bank/', bank_view, name='bank'),
    path('total/', get_total_price, name='total'),
    # path('clearcart/', clear_cart, name='clear_cart'),

]

products/urls.py
from django.urls import path
from .views import(
    product_list_view,
    search_view,
    product_detail_view,
    product_ordering,
    comment_approve,
    comment_remove,

    # ProductDetailSlugView,
)


urlpatterns = [
    path('list/', product_list_view, name='product_list'),
    path('results/', search_view, name='search'),
    path('order/', product_ordering, name='ordering'),

    path('category/<slug:cat_slug>/', product_list_view,
         name='product_list_by_category'),
    path('<pk>/<slug>/',
         product_detail_view, name='product_detail'),
    path('comment/<int:id>/approve',
         comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove',
         comment_remove, name='comment_remove'),

]

cart/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_save, m2m_changed
from django.contrib.auth.models import User

from products.models import Product
from decimal import Decimal

# class CartManager(models.Manager):
#     def new_or_get(self, request):
#         cart_id = request.session.get('cart_id', None)
#         qs = self.get_queryset().filter(id=cart_id)
#         if qs.count() == 1:
#             new_obj = False
#             cart = qs.first()
#             #  fek konam beshe if e paein o hazf kard
#             if request.user.is_authenticated and cart.user is None:
#                 cart.user = request.user
#                 cart.save()
#         else:
#             cart = Cart.objects.create(user=request.user)
#             new_obj = True
#             request.session['cart_id'] = cart.id
#         return cart, new_obj


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(
        max_digits=100000, decimal_places=0, default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    # objects = CartManager()

    def __str__(self):
        return f'{self.user.username} -- با شماره کارت :  {self.id}'

    def add_to_cart(self, product_id):
        product = Product.objects.get(id=product_id)
        try:  # age un product to cart bud yedoone be quantity ezaf kon
            exist_order = CartItem.objects.get(product=product, cart=self)
            exist_order.quantity += 1

            exist_order.save()
        except CartItem.DoesNotExist:  # ye cart jadid besaz product o beriz to un
            new_order = CartItem.objects.create(
                product=product,
                cart=self,
                quantity=1,
            )
            new_order.save()

    def remove_from_cart(self, product_id):
        product = Product.objects.get(pk=product_id)
        try:
            exist_order = CartItem.objects.get(product=product, cart=self)

            if exist_order.quantity > 1:
                exist_order.quantity -= 1
                exist_order.save()
            else:
                exist_order.delete()

        except CartItem.DoesNotExist:
            pass

    def clear_from_cart(self, product_id):
        product = Product.objects.get(pk=product_id)
        try:
            exist_order = CartItem.objects.get(product=product, cart=self)
            product.stock += exist_order.quantity
            product.save()
            exist_order.delete()
        except CartItem.DoesNotExist:
            pass


# def pre_save_cart_reciver(sender, instance, action, *args, **kwargs):
#     if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
#         items = instance.product.all()

#         total = 0
#         for item in items:
#             total += item.price
#         instance.total = total
#         instance.save()


# m2m_changed.connect(pre_save_cart_reciver, sender=Cart.product.through)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def clear_cart(self, request):
        try:
            cart = Cart.objects.get(user=request.user)
            items = CartItem.objects.filter(cart=cart)

            items.delete()
        except CartItem.DoesNotExist:
            pass

    def __str__(self):
        return f'{self.product.title} برای کارت شماره : {self.cart.id}'

        # class Cart(object):

        #     def __init__(self, request):
        #         self.session = request.session
        #         cart = self.session.get(settings.CART_SESSION_ID)

        #         if not cart:  # ye cart e khali ba un session barash besaz
        #             cart = self.session[settings.CART_SESSION_ID] = {}

        #         self.cart = cart

        #     # product o be cart ezafe mikone ya quantity sho update mikone
        #     def add(self, product, quantity, update_quantity=False):
        #         product_id = str(product.id)
        #         cart = self.cart
        #         if product_id not in cart:
        #             cart[product_id] = {'quantity': 0, 'price': str(product.price)}

        #         if update_quantity:
        #             cart[product_id]['quantity'] = quantity

        #         else:
        #             cart[product_id]['quantity'] += quantity

        #         self.save()

        #     def remove(self, product):
        #         product_id = str(product.id)
        #         cart = self.cart
        #         if product_id in cart:
        #             del cart[product_id]

        #             self.save()

        #     def save(self):
        #         # session e cart o update mikone
        #         self.session[settings.CART_SESSION_ID] = self.cart
        #         # session o mark mikone ta motmaen she hamechi save shude
        #         self.session.modified = True

        #     def __iter__(self):
        #         # iterate mikone item haye dakhele cart ro baad product haro az database migire
        #         product_ids = self.cart.keys()
        #         products = Product.objects.filter(id__in=product_ids)

        #         for product in products:
        #             self.cart[str(product.id)]['product'] = product

        #         for item in self.cart.values():
        #             item['price'] = Decimal(item['price'])
        #             item['total_price'] = item['price'] * item['quantity']
        #             yield item

        #     def count(self):
        #         # counter e item haye dakhele cart e
        #         return sum(item['quantity'] for item in self.cart.values())

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        label='تعداد', min_value=1, max_value=20, initial=1)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .models import Cart, CartItem
from products.models import Product
from accounts.forms import UserUpdateForm, ProfileUpdateForm
from accounts.models import Profile


# @login_required
# def maketotal(request):
#     cart = Cart.objects.filter(user=request.user.id, active=True)
#     items = CartItem.objects.filter(cart=cart.first())

#     total = 0
#     count = 0
#     for item in items:
#         total += (item.product.price * item.quantity)
#         count += item.quantity

#     context = {
#         'cart': items,
#         'total': total,
#         'count': count,
#     }
#     return (context['total'])


def add_to_cart(request, product_id):
    if request.user.is_authenticated:
        try:
            product = Product.objects.get(pk=product_id)
        except ObjectDoesNotExist:  # id i ke vojod nadashte bashe vase ye product
            pass

        else:
            try:
                cart = Cart.objects.get(user=request.user, active=True)
            except ObjectDoesNotExist:
                cart = Cart.objects.create(user=request.user)
                cart.save()
            if product.stock == 0:
                product.save()
                messages.success(
                    request, f"محصول  '{product.title}'  به تعدادکافی موجود نیست")
                return redirect('cart:cart')
            else:
                product.stock -= 1
                product.save()
            cart.add_to_cart(product_id)

        return redirect('cart:cart')

    else:
        return redirect('login-view')


def remove_from_cart(request, product_id):
    if request.user.is_authenticated:
        try:
            product = Product.objects.get(pk=product_id)
        except ObjectDoesNotExist:
            pass

        else:
            cart = Cart.objects.get(user=request.user, active=True)
            cart.remove_from_cart(product_id)
            product.stock += 1
            product.save()

        return redirect('cart:cart')
    else:
        return redirect('pages:home-page')


def clear_from_cart(request, product_id):
    if request.user.is_authenticated:
        try:
            product = Product.objects.get(pk=product_id)
        except ObjectDoesNotExist:
            pass

        else:
            cart = Cart.objects.get(user=request.user.id, active=True)
            cart.clear_from_cart(product_id)

        return redirect('cart:cart')
    else:
        return redirect('pages:home-page')


def clear_cart(request):
    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user, active=True)
        items = CartItem.objects.filter(cart=cart)
        for item in items:
            item.clear_cart(request)

        return redirect('cart:cart')
    else:
        return redirect('pages:home-page')


def get_total_price(request):
    cart = Cart.objects.get(user=request.user.id, active=True)
    return cart.total


@login_required
def cart(request):
    message = messages.get_messages(request)
    # cart, new_obj = Cart.objects.new_or_get(request)
    # items = cart.product.all()
    # ---------------[asli]--------------------------------
    try:
        cart = Cart.objects.get(user=request.user.id, active=True)
        items = CartItem.objects.filter(cart=cart)
    except ObjectDoesNotExist:
        cart = Cart.objects.create(user=request.user)
        items = CartItem.objects.filter(cart=cart)
    # -----------------------------------------------------

    total = 0
    count = 0
    for item in items:
        total += (item.product.price * item.quantity)
        count += item.quantity
    cart.total = total
    cart.save()

    context = {
        'cart': items,
        'total': total,
        'count': count,
        'messages': message,

    }

    return render(request, 'cart/detail.html', context)


@login_required
def bank_view(request):
    try:
        cart = Cart.objects.get(user=request.user.id, active=True)
        items = CartItem.objects.filter(cart=cart)
    except ObjectDoesNotExist:
        cart = Cart.objects.create(user=request.user)
        items = CartItem.objects.filter(cart=cart)
    total = cart.total

    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('zarinpal:request')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'cart': items,
        'total': total
    }
    return render(request, 'cart/bank.html', context)


def add_to_cart_product_list(request, product_id):
    if request.user.is_authenticated:
        try:
            product = Product.objects.get(pk=product_id)
        except ObjectDoesNotExist:  # id i ke vojod nadashte bashe vase ye product
            pass

        else:
            try:
                cart = Cart.objects.get(user=request.user, active=True)
            except ObjectDoesNotExist:
                cart = Cart.objects.create(user=request.user)
                cart.save()
            if product.stock == 0:
                product.save()
                messages.success(
                    request, f"محصول  '{product.title}'  به تعدادکافی موجود نیست")
                return redirect('cart:cart')
            else:
                product.stock -= 1
                product.save()
            cart.add_to_cart(product_id)
            messages.success(
                request, f"محصول  '{product.title}' به سبد خرید اضافه شد")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    else:
        return redirect('login-view')


# @require_POST
# def add_to_cart(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     form = CartAddProductForm(request.POST)

#     if form.is_valid():
#         cd = form.cleaned_data
#         cart.add(product=product,
#                  quantity=cd['quantity'], update_quantity=cd['update'])
#     return redirect('cart:cart_detail')

# def remove_from_cart(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     cart.remove(product)
#     return redirect('cart:cart_detail')

# def cart_detail(request):
#     cart = Cart(request)
#     for item in cart:
#         item['update_quantity_form'] = CartAddProductForm(
#             initial={'quantity': item['quantity'], 'update': True})

#     return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}

<br>
<div class="col-md-12">
    {% if messages %}
    {% for message in messages %}

    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <center>
            {{ message }}
        </center>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
</div>
<!-- <h2 class="text-right">سبد خرید شما</h2>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit Price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.img.url }}" alt="">
                </a>
            </td>
            <td>
                {{ product.name }}
            </td>
            <td>
                <form action="{% url 'cart:add_to_cart' product.id %}" method="post">{% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Update">
                </form>
            </td>
            <td><a href="{% url 'cart:remove_from_cart' product.id %}">Remove</a></td>
            <td class="num">{{ item.price }}</td>
            <td class="num">{{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
    </tbody>
</table>
<p class="text-left">
    <a href="{% url 'products:product_list' %}" class="btn btn-warning">Continiue Shopping</a>
</p> -->






<br><br>
<h2 class="text-right">سبد خرید</h2>






{% if total == 0 %}
<p class=" text-right"><b>سبد شما خالی است</b></p>
<div class="col-md-4 offset-md-4">
    <a href="{% url 'products:product_list' %}" class="btn btn-success btn-lg" role="button" aria-pressed="true">اضافه
        کردن محصول <i class="fas fa-cart-plus"></i></a>
</div>
<br>
{% else %}
<br>
<br>
<div class="progress">
    <div class="progress-bar progress-bar-striped bg-light" role="progressbar" style="width: 300%" aria-valuenow="10"
        aria-valuemin="0" aria-valuemax="100"></div>
    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 100%" aria-valuenow="10"
        aria-valuemin="0" aria-valuemax="100"></div>
</div>

<br>
<div class="row">
    <div class="col-md-3 offset-md-5">
        <label class="btn btn-warning" style="height: 40px; width: 90%">
            <p><b>تعداد <span class="badge badge-light">{{ count }}</span> محصول در سبد شما</b></p>
        </label>
    </div>
    <!-- <div class="col-md-3 offset-md-1">
        <a href="{% url 'cart:clear_cart' %}" class="btn btn-danger">خالی کردن سبد <i
                class="fas fa-shopping-cart"></i></a>
    </div> -->

</div>
<br>
<table class="table table-hover text-dark table-light">
    <thead class="bg-dark text-light text-center">
        <tr>
            <th scope="col">کد محصول</th>
            <th scope="col">قیمت محصول</th>
            <th scope="col">تعداد محصول</th>
            <th scope="col">حذف محصول</th>
            <th scope="col">نام محصول</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        {% for item in cart %}
        <tr>
            <th scope="row">{{ item.product.id }}</th>
            <td> <button class="btn btn-secondary mt-3 ml-5">{{ item.quantity }} x
                    {{ item.product.price }}</button>
            </td>
            <td>
                <center>
                    <a class="btn btn-outline-primary mt-3" href="{% url 'cart:remove_from_cart' item.product.id %}"><i
                            class="fas fa-minus-square"></i></a>
                    <button class="btn btn-light mt-3">{{ item.quantity }}
                    </button>
                    <a class="btn btn-outline-primary mt-3" href="{% url 'cart:add_to_cart' item.product.id %}"><i
                            class="fas fa-plus-square"></i></a>
                </center>

            </td>
            <td><a class="btn btn-danger mt-3 ml-5" href="{% url 'cart:clear_from_cart' item.product.id %}">حذف</a>
            </td>

            <td>
                <center> <a class="text-dark mt-3" href="{{ item.product.get_absolute_url }}"> <button
                            class="btn btn-outline-dark mt-3"> <b class="text">{{ item.product.title }}</b></button></a>
                </center>
            </td>
            <td><a href="{{ item.product.get_absolute_url }}">

                    <img class="rounded border border-secondary" src="{{ item.product.image.url }}" alt=""
                        style="width: 100px; height: 80px;">
                </a>
            </td>

        </tr>

        {% endfor %}
        <tr>
            <td class="bg-dark" colspan="1"></td>
            <td class="bg-dark text-light"><b> مبلغ کل : </b> {{ total }} <b> تومان </b></td>
        </tr>

    </tbody>
</table>
<br>
<div class="row">
    <div class="col-md-3">
        <a href="{% url 'cart:bank' %}" class="btn btn-warning btn-lg" role="button" aria-pressed="true">ثبت
            سفارش</a>
    </div>
    <div class="col-md-4 offset-md-2">
        <a href="{% url 'products:product_list' %}" class="btn btn-success btn-lg" role="button"
            aria-pressed="true">اضافه کردن محصولات بیشتر <i class="fas fa-cart-plus"></i></a>
    </div>

</div>




<br>

{% endif %}



{% endblock %}