DigiFood/urls.py
from django.contrib import admin
from django.urls import path, include

from filebrowser.sites import site

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('account/', include('accounts.urls',)),
    path('product/', include(('products.urls', 'products'), namespace='products')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('favorite/', include(('favorites.urls', 'favorites'), namespace='favorites')),
    path('pay/', include(('zarinpal.urls', 'zarinpal'), namespace='zarinpal')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (blog_view,
                    post_list,
                    post_detail,
                    search,

                    post_create,
                    post_update,
                    post_delete,

                    post_like,

                    comment_approve,
                    comment_remove,
                    post_publish,
                    )

urlpatterns = [
    path('', blog_view, name='blog_view'),
    path('posts/', post_list, name='post_list'),
    path('posts/<int:id>/<slug:slug>/detail/', post_detail, name='post_detail'),
    path('posts/<slug:cat_slug>/category/', post_list, name='post_category'),
    path('posts/<int:id>/<slug:slug>/like/', post_like, name='post_like'),

    path('posts/create/', post_create, name='post_create'),
    path('posts/<int:id>/<slug:slug>/update/', post_update, name='post_update'),
    path('posts/<int:id>/<slug:slug>/delete/', post_delete, name='post_delete'),



    # path('posts/add', PostCreate.as_view(), name='post_create'),
    # path('posts/<int:id>/<slug:slug>/update',
    #      PostUpdate.as_view(), name='post_update'),
    # path('posts/<int:id>/<slug:slug>/delete',
    #      PostDelete.as_view(), name='post_delete'),

    path('post/<int:id>/<slug:slug>/publish/',
         post_publish, name='post_publish'),

    path('result/', search, name='search'),

    path('comment/<int:id>/approve',
         comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove',
         comment_remove, name='comment_remove'),

]

cart/urls.py
from django.urls import path
from .views import(
    cart, add_to_cart,
    remove_from_cart,
    clear_from_cart,
    bank_view,
    get_total_price,
    clear_cart,
    add_to_cart_product_list,


)

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<product_id>/', add_to_cart, name='add_to_cart'),
    path('product-list/add/<product_id>/',
         add_to_cart_product_list, name='add_to_cart_product_list'),
    path('remove/<product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/<product_id>/', clear_from_cart, name='clear_from_cart'),
    path('destroy/', clear_cart, name='clear_cart'),
    path('bank/', bank_view, name='bank'),
    path('total/', get_total_price, name='total'),
    # path('clearcart/', clear_cart, name='clear_cart'),

]

favorites/urls.py
from django.urls import path
from .views import favorite_view, add_favorite, clear_from_favorite

urlpatterns = [
    path('', favorite_view, name='favorite_view'),
    path('add/<product_id>/', add_favorite,
         name='favorite_update_view'),
    path('clear/<product_id>/', clear_from_favorite, name='clear_from_favorite'),
]

favorites/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

from products.models import Product

# Create your models here.


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    favorited = models.BooleanField(default=False)

    def add_favorite(self, product_id):
        product = Product.objects.get(id=product_id)
        try:
            exist = FavoriteItem.objects.get(product=product, favorite=self)
            exist.save()
        except FavoriteItem.DoesNotExist:
            new = FavoriteItem.objects.create(product=product, favorite=self)
            new.save()

    def clear_from_favorite(self, product_id):
        product = Product.objects.get(pk=product_id)
        try:
            exist = FavoriteItem.objects.get(product=product, favorite=self)
            exist.delete()
        except FavoriteItem.DoesNotExist:
            pass

    def __str__(self):
        return self.user.username


class FavoriteItem(models.Model):
    favorite = models.ForeignKey(Favorite, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"محصول ' {self.product.title} ' در علاقه مندیهای ({self.favorite.user})"

favorites/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Favorite, FavoriteItem
from products.models import Product
from cart.models import CartItem, Cart

# Create your views here.


@login_required
def favorite_view(request):
    cart = Cart.objects.filter(user=request.user.id, active=True)
    items = CartItem.objects.filter(cart=cart.first())
    try:
        favorite = Favorite.objects.filter(user=request.user.id)
        fav = FavoriteItem.objects.filter(favorite=favorite.first())
    except ObjectDoesNotExist:
        favorite = Favorite.objects.create(user=request.user)
        fav = FavoriteItem.objects.filter(favorite=favorite.first())

    context = {
        'favorite': fav,
        'cart': items,
    }

    return render(request, 'favorites/favorite.html', context)


def add_favorite(request, product_id):
    if request.user.is_authenticated:
        try:
            product = Product.objects.get(pk=product_id)
        except ObjectDoesNotExist:
            pass
        else:
            try:
                favorite = Favorite.objects.get(user=request.user)
            except ObjectDoesNotExist:
                favorite = Favorite.objects.create(user=request.user)
                favorite.save()
            favorite.add_favorite(product_id)
            messages.success(
                request, f"محصول  ' {product.title} '  به لیست علاقه مندیها اضافه شد")

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect('login-view')


def clear_from_favorite(request, product_id):
    if request.user.is_authenticated:
        try:
            product = Product.objects.get(pk=product_id)
        except ObjectDoesNotExist:
            pass

        else:
            favorite = Favorite.objects.get(user=request.user.id)

            favorite.save()
        favorite.clear_from_favorite(product_id)

    else:
        return redirect('pages:home-page')

    return redirect('favorites:favorite_view')

favorites/templates/favorites/favorite.html
{% extends 'base.html' %}

{% block content %}
<br><br>
<h2 class="text-right">علاقه مندیها</h2>
{% if counter == 0 %}
<p class=" text-right"><b>علاقه مند به محصولی نیستید ؟</b></p>
{% else %}

<br><br>
<table class="table table-hover text-dark table-light">
    <thead class="bg-dark text-light text-center">
        <tr>
            <th scope="col">کد محصول</th>
            <th scope="col">اضافه به سبد خرید</th>
            <th scope="col">قیمت محصول</th>

            <th scope="col">حذف محصول</th>
            <th scope="col">نام محصول</th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        {% for item in favorite %}
        <tr>
            <th scope="row">{{ item.product.id }}</th>
            <td><a class="btn btn-warning mt-3 ml-5" href="{% url 'cart:add_to_cart' item.product.id %}"><i
                        class="fas fa-cart-plus"></i></a></td>
            <td> <label class="btn btn-success mt-3 ml-5">
                    {{ item.product.price }}</label>
            </td>

            <td><a class="btn btn-danger mt-3 ml-5"
                    href="{% url 'favorites:clear_from_favorite' item.product.id %}">حذف</a>
            </td>

            <td>
                <center> <a class="text-dark mt-3" href="{{ item.product.get_absolute_url }}"> <label
                            class="btn btn-outline-dark mt-3"> <b class="text">{{ item.product.title }}</b></label></a>
                </center>
            </td>
            <td><a href="{{ item.product.get_absolute_url }}">

                    <img class="rounded border border-secondary offset-md-3" src="{{ item.product.image.url }}" alt=""
                        style="width: 110px; height: 80px">
                </a>
            </td>

        </tr>

        {% endfor %}

    </tbody>
</table>
{% endif %}
<br>


{% endblock %}