DigiFood/urls.py
from django.contrib import admin
from django.urls import path, include

from filebrowser.sites import site

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('account/', include('accounts.urls',)),
    path('product/', include(('products.urls', 'products'), namespace='products')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('favorite/', include(('favorites.urls', 'favorites'), namespace='favorites')),
    path('pay/', include(('zarinpal.urls', 'zarinpal'), namespace='zarinpal')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (blog_view,
                    post_list,
                    post_detail,
                    search,

                    post_create,
                    post_update,
                    post_delete,

                    post_like,

                    comment_approve,
                    comment_remove,
                    post_publish,
                    )

urlpatterns = [
    path('', blog_view, name='blog_view'),
    path('posts/', post_list, name='post_list'),
    path('posts/<int:id>/<slug:slug>/detail/', post_detail, name='post_detail'),
    path('posts/<slug:cat_slug>/category/', post_list, name='post_category'),
    path('posts/<int:id>/<slug:slug>/like/', post_like, name='post_like'),

    path('posts/create/', post_create, name='post_create'),
    path('posts/<int:id>/<slug:slug>/update/', post_update, name='post_update'),
    path('posts/<int:id>/<slug:slug>/delete/', post_delete, name='post_delete'),



    # path('posts/add', PostCreate.as_view(), name='post_create'),
    # path('posts/<int:id>/<slug:slug>/update',
    #      PostUpdate.as_view(), name='post_update'),
    # path('posts/<int:id>/<slug:slug>/delete',
    #      PostDelete.as_view(), name='post_delete'),

    path('post/<int:id>/<slug:slug>/publish/',
         post_publish, name='post_publish'),

    path('result/', search, name='search'),

    path('comment/<int:id>/approve',
         comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove',
         comment_remove, name='comment_remove'),

]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from tinymce import HTMLField

from django.contrib.auth import get_user_model
from accounts.models import Profile


User = get_user_model()

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:list_by_category', args=[self.slug])


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(
        max_length=100, db_index=True, blank=True)
    image = models.ImageField(blank=False, default='post.jpg')
    text = models.TextField()
    content = HTMLField()
    timestamp = models.DateTimeField(auto_now_add=True)
    comment_count = models.IntegerField(default=0)
    view_count = models.IntegerField(default=0)
    like = models.ManyToManyField(User, related_name='like', blank=True)

    categories = models.ManyToManyField(Category)
    special = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return f'{ self.title } توسط { self.author.user }'

    def save(self):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save()

    def approve_comments(self):
        self.comments.filter(approved_comment=True)

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id, self.slug])

    def get_like_url(self):
        return reverse('blog:post_like', args=[self.id, self.slug])

    def get_update_url(self):
        return reverse('blog:post_update', args=[self.id, self.slug])

    def get_delete_url(self):
        return reverse('blog:post_delete', args=[self.id, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)
    is_good = models.PositiveIntegerField(default=0)
    is_bad = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{ self.user.username }---{ self.post.title }'

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(label="افزونه", widget=TinyMCEWidget(
        attrs={'required': False, 'cols': 30, 'rows': 10}))
    title = forms.CharField(label="موضوع")
    slug = forms.SlugField(label="نام نوار ادرس")
    image = forms.ImageField(label="تصویر اصلی پست")
    text = forms.CharField(widget=forms.Textarea, label="نوشته اصلی پست")

    special = forms.BooleanField(label="پست ویژه", required=False)

    class Meta:
        model = Post
        fields = [
            'title', 'slug', 'image', 'text', 'content', 'categories', 'special'
        ]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            'text',
            # 'is_good',
            # 'is_bad',
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect

# from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from django.utils import timezone

# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.contrib import messages

from .models import Post, Comment, Category
from .forms import CommentForm, PostForm

from accounts.models import Profile

# Create your views here.
User = get_user_model()


def get_author(user):
    author = Profile.objects.filter(user=user)
    if author.exists():
        return author.first()
    return None


def cat_count():
    cate = Post.objects.values(
        'categories__title').annotate(Count('categories__title'))
    return cate


def blog_view(request):
    posts = Post.objects.filter(special=True)
    latest = Post.objects.order_by('-timestamp')[:3]
    categories = Category.objects.all().order_by('-id')

    context = {
        'posts': posts,
        'latest': latest,
        'categories': categories,
    }
    return render(request, 'blog/blog-view.html', context)


def post_list(request, cat_slug=None, category=None):
    category_count = cat_count()
    post_list = Post.objects.all().order_by('-timestamp')
    latest = Post.objects.order_by('-timestamp')[:3]

    categories = Category.objects.all().order_by('title')

    if cat_slug:
        category = get_object_or_404(Category, slug=cat_slug)
        post_list = post_list.filter(categories=category)

    paginator = Paginator(post_list, 4)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {
        'post_list': post_list,
        'posts': post_list,
        'page': page,
        'latest': latest,
        'category_count': category_count,
        'categories': categories,
        'category': category,
    }
    return render(request, 'blog/post.html', context)


def post_detail(request, id, slug):
    category_count = cat_count()
    latest = Post.objects.order_by('-timestamp')[:3]
    categories = Category.objects.all().order_by('title')

    post = get_object_or_404(Post, id=id, slug=slug)
    post.view_count = post.view_count + 1
    post.save()

    is_liked = False
    if post.like.filter(id=request.user.id).exists():
        is_liked = True

    form = CommentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect('blog:post_detail', id=id, slug=slug)

    context = {
        'post': post,
        'latest': latest,
        'category_count': category_count,
        'form': form,
        'is_liked': is_liked,
        'categories': categories,
    }
    return render(request, 'blog/post-detail.html', context)


@staff_member_required
def post_create(request):
    title = 'ساخت پست جدید'
    author = get_author(request.user)
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse("blog:post_detail", kwargs={'id': form.instance.id,
                                                                'slug': form.instance.slug}))
    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'blog/post_form.html', context)


@staff_member_required
def post_update(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    title = f'(ویرایش پست ({post.title}'
    author = get_author(request.user)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse("blog:post_detail", kwargs={'id': form.instance.id,
                                                                'slug': form.instance.slug}))
    context = {
        'form': form,
        'title': title,
    }
    return render(request, 'blog/post_form.html', context)


def post_delete(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    post.delete()
    return redirect(reverse('blog:post_list'))


def post_like(request, id, slug, is_liked=False):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, id=request.POST.get('post_id'))

        if post.like.filter(id=request.user.id).exists():
            post.like.remove(request.user)
            is_liked = False
        else:
            post.like.add(request.user)
            is_liked = True
        return redirect(post.get_absolute_url())
    else:
        post = get_object_or_404(Post, id=id, slug=slug)
        messages.success(
            request, f"برای لایک کردن پست  ( {post.title} ) باید ثبت نام/وارد شوید")
        return redirect(post.get_absolute_url())


def search(request):
    category_count = cat_count()
    latest = Post.objects.order_by('-timestamp')[:3]

    result = Post.objects.all()
    query = request.GET.get('q')
    if query:
        result = Post.objects.filter(
            Q(title__icontains=query) |
            Q(text__icontains=query) |
            Q(content__icontains=query)).distinct()

    paginator = Paginator(result, 4)
    page = request.GET.get('page')
    result = paginator.get_page(page)

    context = {
        'query': query,
        'result': result,
        'page': page,
        'latest': latest,
        'category_count': category_count,

    }
    return render(request, 'blog/search.html', context)


@login_required
def post_publish(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    post.publish
    return redirect('blog:post_detail', id=id, slug=slug)


@staff_member_required
def comment_approve(request, id):
    comment = get_object_or_404(Comment, id=id)
    comment.approve()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    # return redirect('blog:post_detail', id=comment.post.id)


@staff_member_required
def comment_remove(request, id):
    comment = get_object_or_404(Comment, id=id)
    # post_id = comment.post.id
    # post_slug = comment.post.slug
    comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    # return redirect('blog:post_detail', id=post_id)

blog/templates/blog/post-detail.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}


{% block content %}
<style>
    .postcontent img {
        width: 100%;
    }
</style>
<div class="row mr-md-0">
    <main class="col-lg-8 offset-md-1">
        <br>
        <div class="container">
            <div class="row">
                <div class="card" style="width: 60rem;">
                    <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="row offset-md-5">
                            {% for cat in post.categories.all %}
                            <p class="text-center text-muted ml-md-2"><b>| {{ cat.title }}</b></p>
                            {% endfor %}
                        </div>
                        <br>

                        <div class="row">
                            {% if request.user.is_staff %}
                            <div class="col-md-5">
                                <a class="btn btn-outline-danger offset-md-1" href="{{ post.get_delete_url }}"> حذف
                                    <ion-icon name="trash">
                                    </ion-icon>

                                </a>
                                <a class="btn btn-outline-info ml-1" href="{{ post.get_update_url }}">
                                    ویرایش
                                    <ion-icon name="create">
                                    </ion-icon>
                                </a>
                            </div>
                            <div class="col-md-7">
                                <h4 class="card-title text-right">{{ post.title }}</h4>
                            </div>
                            {% else %}
                            <div class="col-md-12">
                                <h4 class="card-title text-right">{{ post.title }}</h4>
                            </div>
                            {% endif %}


                        </div>
                        <br>
                        <hr>
                        <div class="col-md-12">
                            {% if messages %}
                            {% for message in messages %}

                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <a class="text-dark" href="{% url 'login-view' %}">
                                    <center>
                                        {{ message }}
                                    </center>
                                </a>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="row justify-content-between">

                            {% if is_liked == False %}
                            <form action="{{ post.get_like_url }}" method="post">{% csrf_token %}
                                <button class="btn btn-outline-danger mt-md-5 ml-md-5" type="submit" name="post_id"
                                    value="{{ post.id }}">
                                    <ion-icon name="heart"></ion-icon><span
                                        class="badge badge-light">{{ post.like.count }}</span>
                                </button>
                            </form>
                            {% else %}
                            <form action="{{ post.get_like_url }}" method="post">{% csrf_token %}
                                <button class="btn btn-danger mt-md-5 ml-md-5" type="submit" name="post_id"
                                    value="{{ post.id }}">
                                    <ion-icon name="heart"></ion-icon><span
                                        class="badge badge-light">{{ post.like.count }}</span>
                                </button>
                            </form>
                            {% endif %}

                            <h5 class="mt-md-5 col-md-1">{{ post.get_comments.count }} <ion-icon name="paper">
                                </ion-icon>
                            </h5>
                            <h5 class="mt-md-5">{{ post.view_count }} <ion-icon name="eye"></ion-icon>
                            </h5>
                            <h5 class="mt-md-5">{{ post.timestamp|timesince }} <ion-icon name="time"></ion-icon>
                            </h5>
                            <h5 class="mt-md-5">{{ post.author.user }} <ion-icon name="person"></ion-icon>
                            </h5>
                            <img class="rounded rounded-circle" src="{{ post.author.image.url }}" alt=""
                                style="width: 100px;height: 100px">

                        </div>
                        <hr>
                        <p class="card-text text-right">{{ post.text }}</p>
                        <br>

                        <div class="postcontent">
                            {{ post.content | safe }}

                        </div>
                        <br><br><br><br>

                        <h3 class="text-center bg-dark text-light" style="height: 50px;width:100%">نظرات</h3>
                        <br>

                        <div class="">

                            {% for comment in post.get_comments %}
                            {% if comment.approved_comment == False and request.user.is_staff %}
                            <div class="media">
                                <div class="media-body">
                                    <h5 class="mt-0 mb-1 text-right"> : {{ comment.user.username }}</h5>


                                    <div class="text-right">
                                        <h6> {{ comment.text }}</h6>

                                    </div>


                                    <div class="text-right">
                                        <hr>

                                        {% if not comment.approved_comment %}
                                        <a class="btn btn-outline-danger"
                                            href="{% url 'blog:comment_remove' comment.id%}">
                                            <ion-icon name="trash">
                                            </ion-icon>

                                        </a>
                                        <a class="btn btn-outline-success ml-1 mr-md-5"
                                            href="{% url 'blog:comment_approve' comment.id%}">
                                            <ion-icon name="checkmark"></ion-icon>
                                        </a>
                                        {% endif %}

                                        <small class="text-muted ">{{ comment.timestamp }}</small>

                                    </div>

                                </div>

                                <img class="rounded rounded-circle ml-3" src="{{ comment.user.profile.image.url }}"
                                    style="width: 9%;height: 80px" alt="...">

                            </div>
                            <hr>
                            {% elif comment.approved_comment == True %}
                            <div class="media">
                                <div class="media-body">
                                    <h5 class="mt-0 mb-1 text-right"> : {{ comment.user.username }}</h5>


                                    <div class="text-right">
                                        <h6> {{ comment.text }}</h6>

                                    </div>


                                    <div class="text-right">
                                        <hr>

                                        <small class="text-muted ">{{ comment.timestamp }}</small>

                                    </div>

                                </div>

                                <img class="rounded rounded-circle ml-3" src="{{ comment.user.profile.image.url }}"
                                    style="width: 78px;height: 80px" alt="...">

                            </div>
                            <hr>
                            {% endif %}
                            {% endfor %}
                            <h4 class="text-right">نظر شما راجب این پست چیه ؟</h4>
                            <br>
                            {% if request.user.is_authenticated %}
                            <form class="needs-validation" action="." method="POST" novalidate>{% csrf_token %}
                                <div class="col-md-5 offset-md-7 ">
                                    <textarea class="form-control text-right" id="validationTextarea"
                                        placeholder="درباره این محصول نظر دهید" name="text" required></textarea>
                                    <div class="invalid-feedback text-right">
                                        ابتدا فیلد مورد نظر را پر کنید
                                    </div>
                                    <br>

                                    <div class="offset-md-7 mt-md-2">
                                        <button class="btn btn-primary" type="submit"> نظر دهید <ion-icon name="create">
                                            </ion-icon></button>
                                    </div>
                            </form>
                            {% else %}
                            <p class="text-right alert alert-warning" role="alert">
                                برای نظر دهی باید <a href="{% url 'login-view' %}">وارد</a> شوید
                            </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <aside class="col-lg-3">
        <!-- ------- search ----- -->
        <br>
        <div>
            <label class="btn btn-light" style="width: 320px">
                <h3 class="text-center"> جستجو در وبلاگ</h3>
            </label>
            <form class="form-inline" action="{% url 'blog:search' %}">
                <button class="btn btn-light my-2 my-sm-0" type="submit">
                    <ion-icon name="search"></ion-icon>
                </button>
                <input class="form-control ml-3 col-md-9" value="{{ request.GET.q }}" type="text" name="q"
                    placeholder="جستجوی نام ، محتوی و ..." aria-label="Search">

            </form>
        </div>
        <!-- ------- Latest posts ------- -->
        <hr>
        <div>
            <label class="btn btn-light" style="width: 320px">
                <h3 class="text-center"> اخرین پست ها </h3>
            </label>
            {% for post in latest %}
            <a class="text-dark" href="{{ post.get_absolute_url }}">
                <div class="card mb-3" style="width: 320px;height: 101px">
                    <div class="row no-gutters">
                        <div class="col-md-5">
                            <img src="{{ post.image.url }}" class="card-img" alt="..."
                                style="height: 100px;width: 133px">
                        </div>
                        <div class="col-md-7">
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ post.title|truncatewords:2 }}</h5>
                                <div class="row">
                                    <div class="col-md-6">
                                        <p class="card-text">
                                            <ion-icon name="paper"></ion-icon>{{ post.get_comments.count }}
                                        </p>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="card-text">
                                            <ion-icon name="eye"></ion-icon>{{ post.view_count }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        <!-- --------- categories --------- -->
        <hr>
        <div>
            <label class="btn btn-light" style="width: 320px">
                <h3 class="text-center">دسته ها</h3>
            </label>

            <div class="row">
                <div class="col-md-1 mt-md-2">
                    {% for cate in category_count %}
                    <label class="btn btn-dark mt-md-2">{{ cate.categories__title__count }}</label>
                    {% endfor %}
                </div>
                <div class="col-md-7 text-right">
                    {% for cat in categories %}
                    <a href="{% url 'blog:post_category' cat.slug %}" class="btn btn-dark mt-md-3"
                        style="width: 290px">{{ cat.title }}</a>
                    {% endfor %}
                </div>

            </div>

        </div>
    </aside>
</div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base2.html' %}


{% block content %}
<center>
    <form action="." method="post">{% csrf_token %}
        <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading text-right">توجه !</h4>
            <p>ایا مطمئن هستید که پست ({{ object.title }}) را می خواهید حذف کنید ؟</p>
            <hr>
            <input type="submit" value="حذف" class="btn btn-danger">
        </div>
    </form>
</center>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="col-md-5 offset-md-4 mt-5 mb-5">
    <h3 class="text-right"> {{ title }} </h3>
    <br>

    {{ form.media }}
    <form class="text-right" action="." method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <img id="id_image" src="{{ post.image.url }}" alt="" name="image">
        <button type="submit" class="btn btn-warning">ذخیره</button>
    </form>


</div>

{% endblock %}