DigiFood/urls.py
from django.contrib import admin
from django.urls import path, include

from filebrowser.sites import site

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('account/', include('accounts.urls',)),
    path('product/', include(('products.urls', 'products'), namespace='products')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('favorite/', include(('favorites.urls', 'favorites'), namespace='favorites')),
    path('pay/', include(('zarinpal.urls', 'zarinpal'), namespace='zarinpal')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (blog_view,
                    post_list,
                    post_detail,
                    search,

                    post_create,
                    post_update,
                    post_delete,

                    post_like,

                    comment_approve,
                    comment_remove,
                    post_publish,
                    )

urlpatterns = [
    path('', blog_view, name='blog_view'),
    path('posts/', post_list, name='post_list'),
    path('posts/<int:id>/<slug:slug>/detail/', post_detail, name='post_detail'),
    path('posts/<slug:cat_slug>/category/', post_list, name='post_category'),
    path('posts/<int:id>/<slug:slug>/like/', post_like, name='post_like'),

    path('posts/create/', post_create, name='post_create'),
    path('posts/<int:id>/<slug:slug>/update/', post_update, name='post_update'),
    path('posts/<int:id>/<slug:slug>/delete/', post_delete, name='post_delete'),



    # path('posts/add', PostCreate.as_view(), name='post_create'),
    # path('posts/<int:id>/<slug:slug>/update',
    #      PostUpdate.as_view(), name='post_update'),
    # path('posts/<int:id>/<slug:slug>/delete',
    #      PostDelete.as_view(), name='post_delete'),

    path('post/<int:id>/<slug:slug>/publish/',
         post_publish, name='post_publish'),

    path('result/', search, name='search'),

    path('comment/<int:id>/approve',
         comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove',
         comment_remove, name='comment_remove'),

]

cart/urls.py
from django.urls import path
from .views import(
    cart, add_to_cart,
    remove_from_cart,
    clear_from_cart,
    bank_view,
    get_total_price,
    clear_cart,
    add_to_cart_product_list,


)

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<product_id>/', add_to_cart, name='add_to_cart'),
    path('product-list/add/<product_id>/',
         add_to_cart_product_list, name='add_to_cart_product_list'),
    path('remove/<product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear/<product_id>/', clear_from_cart, name='clear_from_cart'),
    path('destroy/', clear_cart, name='clear_cart'),
    path('bank/', bank_view, name='bank'),
    path('total/', get_total_price, name='total'),
    # path('clearcart/', clear_cart, name='clear_cart'),

]

favorites/urls.py
from django.urls import path
from .views import favorite_view, add_favorite, clear_from_favorite

urlpatterns = [
    path('', favorite_view, name='favorite_view'),
    path('add/<product_id>/', add_favorite,
         name='favorite_update_view'),
    path('clear/<product_id>/', clear_from_favorite, name='clear_from_favorite'),
]

products/urls.py
from django.urls import path
from .views import(
    product_list_view,
    search_view,
    product_detail_view,
    product_ordering,
    comment_approve,
    comment_remove,

    # ProductDetailSlugView,
)


urlpatterns = [
    path('list/', product_list_view, name='product_list'),
    path('results/', search_view, name='search'),
    path('order/', product_ordering, name='ordering'),

    path('category/<slug:cat_slug>/', product_list_view,
         name='product_list_by_category'),
    path('<pk>/<slug>/',
         product_detail_view, name='product_detail'),
    path('comment/<int:id>/approve',
         comment_approve, name='comment_approve'),
    path('comment/<int:id>/remove',
         comment_remove, name='comment_remove'),

]

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


# Create your models here.

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(blank=True)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = 'کتگوری'
        verbose_name_plural = 'کتگوری ها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_list_by_category', args=[self.slug])


class ProductManager(models.Manager):
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)  # Product.objects. ...
        if qs.count() == 1:
            return qs.first()
        return None

    # def get_queryset(self):
    #     return ProductQuerySet(self.model, using=self.db)

    # def search(self, query=None):
    #     return self.get_queryset().search(query=query)


class Product(models.Model):
    # ye many to one relationship e(ke mige ye product moteallegh be ye category e , ye category shamele chand product e)
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, db_index=True)
    # baraye sakhte URL ha estefade mishe
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=100000, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    special = models.BooleanField(default=False)
    special2 = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    image = models.ImageField(blank=False, default='product.jpg')
    image2 = models.ImageField(blank=True, null=True, default='product.jpg')
    image3 = models.ImageField(blank=True, null=True, default='product.jpg')

    objects = ProductManager()

    class Meta:
        ordering = ('-created',)
        # chun ma mikhaym bar asas e id o slug to query biarim
        index_together = (('id', 'slug'),)
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.id, self.slug])

    def approve_comments(self):
        self.comment.filter(approved_comment=True)

    @property
    def get_comments(self):
        return self.comment.all().order_by('-timestamp')


class ProductComment(models.Model):
    product = models.ForeignKey(
        Product, related_name='comment', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)
    is_good = models.BooleanField(default=False)
    is_bad = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'کامنت محصوت'
        verbose_name_plural = 'کامنت ها'

    def __str__(self):
        return f'{ self.user.username }---{ self.product.title }'

    def approve(self):
        self.approved_comment = True
        self.save()

    def good(self):
        self.is_good = True
        self.save()

    def bad(self):
        self.is_bad = True
        self.save()

    def get_absolute_url(self):
        return reverse('product_list')

products/forms.py
from django import forms
from .models import ProductComment


class CommentForm(forms.ModelForm):

    class Meta:
        model = ProductComment
        fields = [
            'text',
            'is_good',
            'is_bad',
        ]

products/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.db.models import Q
from .models import Product, Category, ProductComment
from favorites.models import FavoriteItem, Favorite
from django.views.generic import View
from cart.models import Cart, CartItem
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required

from .filters import ProductFilter
from .forms import CommentForm
from accounts.models import Profile


# list product ha.


def product_list_view(request, cat_slug=None):
    message = messages.get_messages(request)
    cart = Cart.objects.filter(user=request.user.id, active=True)
    items = CartItem.objects.filter(cart=cart.first())  # baraye counter
    category = None

    categories = Category.objects.all().order_by(
        '-id')  # kolle category ha bedoone slug
    products = Product.objects.filter(available=True)

    paginator = Paginator(products, 6)  # paginator baraye P_list_view
    page = request.GET.get('page')

    # baraye dast resi be product e har page... age ino nazarim to har page faqat 3 post e akha ro neshun mide
    products = paginator.get_page(page)
    filter = ProductFilter(
        request.GET, queryset=Product.objects.all())
    if cat_slug:
        products = Product.objects.filter(available=True)
        # age ino dobare taarif nakonim products o paginator minine o dg produvt.obj bar nemigardoone
        category = get_object_or_404(Category, slug=cat_slug)
        # mire donbale product aei ke category e bala ro daran o peyda mikone
        products = products.filter(category=category)
        paginator = Paginator(products, 6)  # paginator baraye C_list_view
        page = request.GET.get('page')
        products = paginator.get_page(page)

    context = {
        'category': category,
        'categories': categories,
        'products': products,

        'page': page,
        'cart': items,
        'message': message,
        'filter': filter,


    }
    return render(request, 'products/products_list.html', context)

#  ----------------- class detail base view ke nemifahmam------------

# class ProductDetailSlugView(DetailView):
#     model = Product  # beja get_object

#     context_object_name = 'product'
#     template_name = 'products/product_detail.html'

#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(*args, **kwargs)
#         cart_obj, new_obj = Cart.objects.new_or_get(self.request)
#         context['cart'] = cart_obj
#         return context

# ----- get_object ham nabashe baz okeye ------------------

    # def get_object(self, *args, **kwargs):
    #     request = self.request
    #     message = messages.get_messages(request)
    #     slug = self.kwargs.get('slug_detail')
    #     try:
    #         instance = Product.objects.get(slug=slug)
    #     except Product.DoesNotExist:
    #         raise Http404('پیدا نشد!')
    #     except Product.MultipleObjects.Returned:
    #         qs = Product.objects.filter(slug=slug)
    #         instance = qs.first()
    #     except:
    #         raise Http404('hmmmm...')
    #     return instance

#  ---------------func e khudam...------------------------


def product_detail_view(request, pk, slug):
    cart = Cart.objects.filter(user=request.user.id, active=True)
    items = CartItem.objects.filter(cart=cart.first())

    product = get_object_or_404(Product, pk=pk, slug=slug)
    fav_counter = FavoriteItem.objects.filter(product=product)
    message = messages.get_messages(request)

    same_cat = Product.objects.filter(
        category=product.category).exclude(pk=product.pk)[:3]

    form = CommentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.instance.product = product
            form.save()
            return redirect('products:product_detail', pk=pk, slug=slug)

    context = {
        'product': product,
        'cart': items,
        'fav_counter': fav_counter,
        'message': message,
        'form': form,
        'same_cat': same_cat,

    }
    return render(request, 'products/product_detail.html', context)
# --------------------------------------------------------------


def search_view(request):
    cart = Cart.objects.filter(user=request.user.id, active=True)
    items = CartItem.objects.filter(cart=cart.first())
    categories = Category.objects.all().order_by(
        '-id')

    query = request.GET.get('q')
    result = Product.objects.filter(available=True)
    # user_filter = UserFilter(request.GET, queryset=result)
    if query:
        result = Product.objects.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(slug__icontains=query)
        ).distinct()

    paginator = Paginator(result, 6)
    page = request.GET.get('page')
    result = paginator.get_page(page)

    context = {
        'query': query,
        'result': result,
        'page': page,
        'item': result,
        'cart': items,
        'categories': categories,
        # 'filter': user_filter,
    }

    return render(request, 'products/search.html', context)


class PaginatedFilterViews(View):
    def get_context_data(self, **kwargs):
        context = super(PaginatedFilterViews, self).get_context_data(**kwargs)
        if self.request.GET:
            querystring = self.request.GET.copy()
            if self.request.GET.get('page'):
                del querystring['page']
            context['querystring'] = querystring.urlencode()
        return context


def product_ordering(request):
    cart = Cart.objects.filter(user=request.user.id, active=True)
    items = CartItem.objects.filter(cart=cart.first())
    categories = Category.objects.all().order_by(
        '-id')

    product = Product.objects.filter(available=True)
    filter = ProductFilter(
        request.GET, queryset=product)

    paginator = Paginator(filter, 6)
    page = request.GET.get('page')
    # funds = paginator.get_page(page)

    context = {
        'filter': filter,
        # 'page': funds,
        'categories': categories,
        'cart': items,
    }
    return render(request, 'products/filter.html', context)


# -----------product comment -----------------
def get_author(user):
    author = Profile.objects.filter(user=user)
    if author.exists():
        return author[0]
    return None


@staff_member_required
def comment_approve(request, id):
    comment = get_object_or_404(ProductComment, id=id)
    comment.approve()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    # return redirect('blog:post_detail', id=comment.post.id)


@staff_member_required
def comment_remove(request, id):
    comment = get_object_or_404(ProductComment, id=id)
    # post_id = comment.post.id
    # post_slug = comment.post.slug
    comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    # return redirect('blog:post_detail', id=post_id)

products/templates/products/filter.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<div class="col-md-12">
    {% if messages %}
    {% for message in messages %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <center>
            {{ message }}
        </center>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
</div>




<br>
<div class="row">
    <div class="btn-group col-md-6" role="group" aria-label="Basic example">
        {% for cat in categories %}
        <a href="{% url 'products:product_list_by_category' cat.slug %}" style="height: 45px"
            class="btn btn-secondary">{{ cat.name }}</a>
        {% endfor %}
        <a href="{% url 'products:product_list' %}" style="height: 45px" class="btn btn-danger">تمام محصولات</a>
    </div>
    <div class="col-md-3  offset-md-3">
        <form class="form-inline" method="GET" action="{% url 'products:search' %}">

            <input class="form-control mr-sm-2 text-right" type="search" name="q" placeholder="جستجو"
                value="{{ request.GET.q }}" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>

        </form>
    </div>
</div>



<hr>

<form action="{% url 'products:ordering' %}" method="get">
    <div class="row">
        <div class="col-md-2 offset-md-1 text-right">
            {{ filter.form.special|as_crispy_field }}
        </div>
        <div class="col-md-2 text-right">
            {{ filter.form.ordering2|as_crispy_field }}
        </div>
        <div class="col-md-2 text-right">
            {{ filter.form.ordering|as_crispy_field }}
        </div>
        <div class="col-md-2 text-right">
            {{ filter.form.ordering3|as_crispy_field }}
        </div>

        <div class="col-md-2 offset-md-1">
            <button type="submit" class="btn btn-primary mt-md-4"><i class="fas fa-filter"></i>مرتب سازی</button>
        </div>
    </div>

</form>
<!-- {% if result %}
<div>
    <p class="text-right"><b>تعداد {{ result|length }} محصول پیدا شد </b></p>
</div>
{% else %}

{% endif %} -->
<hr>
<center>
    <div class="row justify-content-end">
        {% for product in filter.qs %}
        {% if product.stock == 0 %}


        <div class="col-md-4">
            <div class="card shadow-sm p-4 mb-4 bg-light" style="width: 330px; height:  26rem;">
                <a href="">
                    <img src="{{ product.image.url }}" class="card-img-top border border-dark" style="height: 182px;"
                        alt="name"></a>
                <div class="card-body" style="height: 200px;">
                    <h5 class="card-title" style="height: 50px;">
                        <center>{{ product.title }}</center>
                    </h5>
                    <p class="card-text text-right font-weight-bold">به تعداد کافی موجود نیست</p>
                    <div class="col-md-14 mr-1">
                        <div class="card-footer rounded" style="width: 109%;">

                            <div class="row">
                                <div class="col-md-8">
                                    <small class="text-muted">
                                        دسته: {{ product.category.name }}
                                    </small>
                                </div>
                                <div class="col-md-2 ">
                                    <a href="{{ product.get_absolute_url }}"
                                        class="btn btn-secondary disabled">جزئیات</a>
                                </div>
                                <div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% else %}

        <div class="col-md-4 mb-md-1 mr-0">
            <div class="card shadow-lg p-4 mb-4 bg-white" style="width: 330px; height:  28rem;">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}" class="card-img-top border border-dark" style="height: 182px;"
                        alt="{{product.title}}"></a>
                <div class="card-body" style="height: 200px;">
                    <h5 class="card-title" style="height: 50px;">
                        <center>{{ product.title }}</center>
                    </h5>
                    {% if product.special == True or product.special2 == True %}
                    <p class="bg-danger text-center text-white" style="width: 100%;"><strong>* پیشنهاد
                            ویژه *</strong></p>
                    {% else %}
                    <p class="text-center text-white" style="width: 100%;"><strong>-</strong></p>
                    {% endif %}
                    <div class="row">
                        <div class="col-md-2 mb-2">
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-outline-danger" data-toggle="modal"
                                data-target="#{{ product.slug }}" data-toggle="tooltip" data-placement="bottom"
                                title="نمایش سریع جزئیات">
                                <i class="fas fa-info-circle"></i>
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="{{product.slug}}" tabindex="-1" role="dialog"
                                aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content" style="height: 300px;width: 110%">
                                        <div class="modal-header">

                                            <h5 class="modal-title ml-5" id="exampleModalLabel"
                                                style="padding-left: 200px">
                                                {{ product.title}}
                                            </h5>


                                        </div>
                                        <div class="modal-body">
                                            <div class="row">



                                                <div class="col-md-4">
                                                    <img src="{{ product.image.url }}" alt="{{ product.title}}"
                                                        style="height: 110px;width: 100%">
                                                </div>

                                                <div class="col-md-6">
                                                    <div class="card">
                                                        <div class="card-body">
                                                            <p class="card-text text-right">
                                                                {{ product.description|truncatewords:10 }}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2">
                                                    <div>
                                                        <button type="button"
                                                            class="col-md-10 ml-md-2 btn btn-outline-dark"
                                                            data-dismiss="modal" data-toggle="tooltip"
                                                            data-placement="right" title="بستن"><i
                                                                class="fas fa-times"></i></button>
                                                    </div>
                                                    <div>
                                                        <a href="{% url 'favorites:favorite_update_view' product.id %}">
                                                            <button class="btn btn-danger mt-md-3 col-md-10 ml-md-2"
                                                                data-toggle="tooltip" data-placement="right"
                                                                title="اضافه به علاقه مندیها"> <i class="fas fa-heart">
                                                                </i>
                                                            </button>

                                                        </a>
                                                    </div>
                                                    <div>
                                                        <a href="{% url 'cart:add_to_cart_product_list' product.id %}">
                                                            <button class="btn btn-warning mt-md-3 col-md-10 ml-md-2"
                                                                data-toggle="tooltip" data-placement="right"
                                                                title="اضافه به سبد خرید"><i
                                                                    class="fas fa-cart-plus"></i>
                                                            </button>

                                                        </a>
                                                    </div>


                                                </div>

                                            </div>

                                            <div class="card-footer mt-md-2" style="height: 50px;">
                                                <h5 class="card-title text-right col-md-7 offset-md-2">
                                                    قیمت :
                                                    {{ product.price }} تومان</h5>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 offset-md-2">
                            <p class="card-text text-center font-weight-bold" style="width: 110%"> قیمت:
                                {{ product.price }} تومان</p>
                        </div>
                    </div>
                    <div class="col-md-14 mr-1">
                        <div class="card-footer rounded" style="width: 109%;">

                            <div class="row">
                                <div class="col-md-8">
                                    <small class="text-muted">
                                        دسته: {{ product.category.name }}
                                    </small>
                                </div>
                                <div class="col-md-2 ">
                                    <a href="{{ product.get_absolute_url }}" class="btn btn-outline-primary">جزئیات</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endif %}
        {% endfor %}

    </div>
</center>



<div class="col-md-7 offset-md-4">
    {% if filter_list.has_previous %}
    <a class="btn btn-outline-warning mb-4" href="?page=1{% if query %}&q={{query}}{% endif %}"><i
            class="fas fa-angle-double-left"></i>اولین</a>
    <a class="btn btn-outline-warning mb-4"
        href="?page={{ filter_list.previous_page_number }}{% if query %}&q={{query}}{% endif %}"><i
            class="fas fa-chevron-circle-left"></i>قبلی</a>
    {% endif %}

    {% for num in filter_list.paginator.page_range %}
    {% if products.number == num %}
    <a class="btn btn-dark mb-4" href="?page={{ num }}{% if query %}&q={{query}}{% endif %}">{{ num }}</a>
    {% elif num > filter_list.number|add:'-3' and num < filter_list.number|add:'3' %}
    <a class="btn btn-outline-secondary mb-4" href="?page={{ num }}{% if query %}&q={{query}}{% endif %}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if filter_list.has_next %}
    <a class="btn btn-outline-warning mb-4"
        href="?page={{ filter_list.next_page_number }}{% if query %}&q={{query}}{% endif %}"><i
            class="fas fa-chevron-circle-right"></i>بعدی</a>
    <a class="btn btn-outline-warning mb-4"
        href="?page={{ filter_list.paginator.num_pages }}{% if query %}&q={{query}}{% endif %}"><i
            class="fas fa-angle-double-right"></i>اخرین</a>
    {% endif %}
</div>
{% endblock %}